package pistonmc.extracellsrenderfix;

// This file is automatically generated
// Do not edit this file manually

public interface ModInfo {
    String Id = "extracellsrenderfix";
    String Version = "1.7.0";
    String Group = "pistonmc.extracellsrenderfix";
    String GroupInternal = "pistonmc/extracellsrenderfix";
}

