version: '3'

tasks:
  setup:
    desc: Setup development env after cloning
    cmds:
    - ./gradlew setupDecompWorkspace
    - powershell -NoProfile -c "mcmod eclipse"
    - powershell -NoProfile -c "mcmod devget CodeChickenCore-1.7.10-1.0.7.47-dev.jar"
    - powershell -NoProfile -c "mcmod devget CodeChickenLib-1.7.10-1.1.3.138-dev.jar"
    - powershell -NoProfile -c "mcmod devget NotEnoughItems-1.7.10-1.0.5.120-dev.jar"
    - powershell -NoProfile -c "mcmod devget appliedenergistics2-rv2-stable-10-dev.jar"
    - powershell -NoProfile -c "mcmod devget ExtraCells-deobf-1.7.10-2.3.14b197.jar"
    - powershell -NoProfile -c "mcmod devget industrialcraft-2-2.2.823-experimental-dev.jar"
    - powershell -NoProfile -c "mcmod devget gregtech-5.09.33-dev.jar"
