package pistonmc.extracellsrenderfix.coremod;

// This file is automatically generated
// Do not edit this file manually

public interface CoremodInfo {
    String Id = "extracellsrenderfix";
    String Version = "1.7.0";
    String Group = "pistonmc.extracellsrenderfix";
    String GroupInternal = "pistonmc/extracellsrenderfix";
    String CoremodGroup = "pistonmc.extracellsrenderfix.coremod";
    String CoremodGroupInternal = "pistonmc/extracellsrenderfix/coremod";
}

