package com.piston.mc.extracellsrenderfix.coremod;
// This file is automatically generated
// Do not edit this file directly
public interface CoremodInfo {
    String Id = "extracellsrenderfix";
    String Version = "1.6.0";
    String Group = "com.piston.mc.extracellsrenderfix";
    String GroupSlashed = "com/piston/mc/extracellsrenderfix";
    String CoremodGroup = "com.piston.mc.extracellsrenderfix.coremod";
    String CoremodGroupSlashed = "com/piston/mc/extracellsrenderfix/coremod";
}
