package com.piston.mc.extracellsrenderfix;
// This file is automatically generated
// Do not edit this file directly
public interface ModInfo {
    String Id = "extracellsrenderfix";
    String Version = "1.6.0";
    String Group = "com.piston.mc.extracellsrenderfix";
    String GroupSlashed = "com/piston/mc/extracellsrenderfix";
}
